server:
  port: 80

eureka:
  client:
    register-with-eureka: true # 是否向注册中心注册自己
    fetch-registry: true #是否向eureka server抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka # 向哪个注册中心注册服务

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler: # 采样率介于0到1之间
        probability: 1
