server:
  port: 3344

spring:
  application:
    name: cloud-config-center # 注册金eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rivers1998/springcloud-config.git # github上git仓库的名字
          search-paths:
            - springcloud-config # 搜索目录
      label: master # 读取分支

# rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# rabbitmq相关配置,暴露bus刷新配置配置的端点
management:
  endpoints: # 暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

